# Generated by Django 2.2.3 on 2019-07-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papical_back_end', '0003_auto_20190708_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
