# Generated by Django 2.2.3 on 2019-07-09 14:37

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('papical_back_end', '0004_auto_20190708_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='event',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='name',
        ),
        migrations.AddField(
            model_name='event',
            name='tag',
            field=taggit.managers.TaggableManager(blank=True, help_text='Separate each Tag with a comma.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='interest',
            name='interest',
            field=taggit.managers.TaggableManager(blank=True, help_text='Separate each interest with a comma.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Interests'),
        ),
    ]
