# Generated by Django 2.2.3 on 2019-07-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papical_back_end', '0004_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
