# Generated by Django 2.2.3 on 2019-07-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papical_back_end', '0004_user_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
