# Generated by Django 2.2.3 on 2019-07-10 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papical_back_end', '0005_freetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='freetime',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='freetime', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
