# Generated by Django 2.2.3 on 2019-07-11 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papical_back_end', '0005_auto_20190710_1642'),
        ('papical_back_end', '0006_freetime_creator'),
    ]

    operations = [
    ]
