# Generated by Django 2.2.3 on 2019-07-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papical_back_end', '0007_merge_20190712_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-Binary'), ('PN', 'Prefer not to say')], max_length=2, null=True),
        ),
    ]
